#!/usr/bin/env bash

TIMESPAN=1

getGlobalRx() {
    sum=0
    for iface in `ls /sys/class/net`; do
	current=$(($current+`cat /sys/class/net/$iface/statistics/rx_bytes`))
    done
    echo $current
}

getGlobalTx() {
    sum=0
    for iface in `ls /sys/class/net`; do
	current=$(($current+`cat /sys/class/net/$iface/statistics/tx_bytes`))
    done
    echo $current
}

BR1=`getGlobalRx`
BT1=`getGlobalTx`

sleep $TIMESPAN

BR2=`getGlobalRx`
BT2=`getGlobalTx`


DOWNKB=$(((($BR2-$BR1) / $TIMESPAN) /1024))
UPKB=$(((($BT2-$BT1) / $TIMESPAN) /1024))

echo "D ${DOWNKB}KB/s | U ${UPKB}KB/s"

exit 0
